#!/usr/bin/env bash
# Run Nginx as Nginx
# Server bug fixing
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
# Restart
su nginx -s /bin/bash -c 'service nginx restart'
